# Etapa 1: build de TypeScript
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY receptor.ts tsconfig.json ./
RUN npm run build

# Etapa 2: imagen final
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/receptor.js"]
